create table if not exists public.product_sections (
  id bigint generated by default as identity primary key,
  name text not null
);

alter table public.product_sections add column if not exists image_url text not null default '';
alter table public.product_sections add column if not exists sort_order integer not null default 0;
alter table public.product_sections add column if not exists is_active boolean not null default true;
alter table public.product_sections add column if not exists created_at timestamptz not null default now();
alter table public.product_sections add column if not exists updated_at timestamptz not null default now();

alter table public.product_sections enable row level security;

grant select on table public.product_sections to anon, authenticated;
grant select, insert, update, delete on table public.product_sections to service_role;

drop policy if exists "Public can read active product sections" on public.product_sections;
drop policy if exists "Enable read access for all users" on public.product_sections;
create policy "Public can read active product sections"
on public.product_sections
for select
to anon, authenticated
using (is_active = true);

create index if not exists product_sections_store_order_idx
on public.product_sections (is_active, sort_order, created_at);
